/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/countdown`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Calendrier` | `/Calendrier`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Ressources` | `/Ressources`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ToDo` | `/ToDo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/countdown`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Calendrier` | `/Calendrier`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Ressources` | `/Ressources`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ToDo` | `/ToDo`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/countdown${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Calendrier${`?${string}` | `#${string}` | ''}` | `/Calendrier${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Ressources${`?${string}` | `#${string}` | ''}` | `/Ressources${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ToDo${`?${string}` | `#${string}` | ''}` | `/ToDo${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/countdown`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Calendrier` | `/Calendrier`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Ressources` | `/Ressources`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ToDo` | `/ToDo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
